language: node_js

node_js:
   - "11"

cache: yarn

script: # the build step
   - yarn run build

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: master
  fqdn: www.hackregina.com
  on:
    branch: develop
